# SavageFactions by ProSavage
# Report issues: https://github.com/ProSavage/SavageFactions/issues/new
# Live support: https://discord.gg/W9dv9WP
# Spigot Site: https://www.spigotmc.org/resources/savagefactions-factionsuuid-reimagined-1-7-1-12.52891/
# Website: http://www.prosavage.net/
# CI: http://ci.prosavage.net/
# Wiki: http://wiki.prosavage.net/display/savagefactions
# Make sure to check the wiki mentioned above before making a issue on github or asking for help in the discord chat!
# There are additional options present in the conf.json file.
# 
# Made with love <3
# 
# Debug
# Turn this on if you are having issues with something and working on resolving them.
# This will spam your console with information that is useful if you know how to read the source.
# It's suggested that you only turn this on at the direction of a developer.
debug: false
findfactionsexploit:
  cooldown: 2000
  log: false
default-relation: neutral
portals:
  limit: false
  minimum-relation: MEMBER
max-warps: 5
warp-cost:
  enabled: false
  setwarp: 5
  delwarp: 5
  warp: 5
enable-faction-flight: true
ffly:
  Particles:
    Enabled: true
    Enable-While-Vanished: true
  AutoEnable: true
fly-falldamage-cooldown: 10
disable-pistons-in-territory: false
tooltips:
  list:
  - '&6&l* &eLeader: &7{leader}'
  - '&6&l* &eClaims: &7{chunks}'
  - '&6&l* &ePower: &7{power}/{maxPower}'
  - '&6&l* &eMembers: &7{online}/{members}'
  show:
  - '&6&l* &eUsername: &7{name}'
  - '&6&l* &eRank: &7{group}'
  - '&6&l* &eBalance: &7${balance}'
  - '&6&l* &eLast Seen:&7 {lastSeen}'
  - '&6&l* &ePower: &7{player-power}/{player-maxpower}'
scoreboard:
  also-send-chat: true
  expiration: 7
  finfo-enabled: false
  finfo:
  - '&6Power'
  - '{power}'
  - '&3Members'
  - '{online}/{members}'
  - '&4Leader'
  - '{leader}'
  - '&bTerritory'
  - '{chunks}'
  default-enabled: false
  default-title: '&cSavageFactions'
  default-update-interval: 2
  default-prefixes: true
  default:
  - '&7&m--------------------------'
  - '&4&lFaction Info &8»'
  - ' &8> &cLeader&7: &f{leader}'
  - ' &8> &cMembers&7: &f{online}&7/&f{members}'
  - ' &8> &cPower&7: &f{power}&7/&f{maxPower}'
  - '&m'
  - '&4&lFaction Stats &8»'
  - ' &8> &cKills&7: &f{faction-kills}'
  - ' &8> &cDeaths&7: &f{faction-deaths}'
  - ' &8> &cBalance&7: &f{faction-balance}'
  - ''
  - ' &8> &cYour Balance&7: &f{balance}'
  - '&7&m---------------------------'
  factionless-enabled: true
  factionless:
  - '&7&m--------------------------'
  - '&4&lInformation &8»'
  - ' &8> &cPlayer&7: &f{name}'
  - ' &8> &cRank&7: &f{group}'
  - ' &8> &cBalance&7: &f${balance}'
  - '&m'
  - '&4&lServer Info &8» '
  - ' &8» &cIFaction: &fN/A'
  - ' &8» &cOnline Players&7: &f{total-online}'
  - '&7&m---------------------------'
warmups:
  f-home: 15
  f-warp: 10
  f-fly: 0
  f-checkpoint: 10
  f-banner: 10
max-relations:
  enabled: true
  ally: 1
  truce: 0
  neutral: -1
  enemy: -1
world-border:
  buffer: 0
hcf:
  raidable: false
  dtr: false
  allow-overclaim: true
  powerfreeze: 0
  buffer-zone: 0
  stuck:
    delay: 30
    radius: 10
show:
- '&8&m--------------&7 &8<&e{faction}&8> &8&m--------------'
- '&6 * &eOwner &7{leader}'
- '&6 * &eDescription &7{description}'
- '&6 * &eLand / Power / Max Power: &7{chunks} &8/ &7{power} &8/ &7{maxPower}'
- '&6 * &eFounded &7{create-date}'
- '&6 * &eBalance &f{faction-balance}'
- '&6 * &eAllies &c{allies-list}'
- '&6 * &eEnemies &c{enemies-list}'
- '&6 * &eOnline Members &8(&7{online}/{members}&8) &7{online-list}'
- '&6 * &eOffline Members &8(&7{offline}/{members}&8) &7{offline-list}'
- '&6 * &eBans &7{faction-bancount}'
- '&8&m----------------------------------------'
minimal-show: false
show-exempt:
- Wilderness
map:
- '&6* &eFaction &7{faction}'
- '&6* &eOwner &7{leader}'
- '&6* &eLand / Power / Max Power: &7{chunks} &8/ &7{power} &8/ &7{maxPower}'
- '&6* &eAllies &c{allies-list}'
- '&6* &eEnemies &c{enemies-list}'
- '&6* &eOnline Members &8(&7{online}/{members}&8) {online-list}'
- '&6* &eOffline Members &7{offline-list}'
list:
  header: '&8&m-----------------&r &8< &eFaction List &8(&7{pagenumber}/{pagecount}&8)
    &8> &m-----------------'
  factionless: '&7&o(( There are currently &f{total-online} &7&oPlayers online right
    now! ))'
  entry: '{faction} &8(&7{online}/{members}&8)  &eLand / Power / Max Power &f{chunks}&7/&f{power}&7/&f{maxPower}'
use-old-help: false
help:
  '1':
  - '&7&m----------------------------------------------------'
  - '&6&lFactions Help &8- &f(1/2)               '
  - '&7&m----------------------------------------------------'
  - '&e/f create &f<name> &8- &7Create your own faction.'
  - '&e/f who &f<name> &8- &7Show faction information.'
  - '&e/f tag &f<name> &8- &7Change your faction name.'
  - '&e/f join &f<name> &8- &7Join to the faction.'
  - '&e/f list &8- &7List all factions.'
  - '&e/f top &8- &7View the richest factions.'
  - '&e/f map &8- &7Map of the surrounding area, click chunks to claim.'
  - '&e/f sethome &8- &7Set your faction home.'
  - '&e/f home &8- &7Go to your faction home.'
  - '&e/f title &f<playername> <title> &8- &7Set a player''s title, color codes supported.'
  - '&e/f ban &8- &7Ban a member from your faction.'
  - '&e/f unban &8- &7Unban a member from your faction.'
  - '&e/f banlist &8- &7List banned players from your faction.'
  - '&e/f lowpower &8- &7List player with power under max from your faction.'
  - '&e/f coords &8- &7Broadcast your location to your faction.'
  - '&e/f showclaims &8- &7List all claims from your faction.'
  - '&7&m--------------------&r &e/f help 2 &7&m-----------------------'
  '2':
  - '&7&m----------------------------------------------------'
  - '&6&lFactions Help &8- &f(2/2)               '
  - '&7&m----------------------------------------------------'
  - '&e/f leave &8- &7Leave your faction.'
  - '&e/f invite &f<playerName> &8- &7Invite a player to your faction.'
  - '&e/f deinvite &f<playerName> &8- &7Revoke invitation to player.'
  - '&e/f claim &8- &7Claim a land for your faction.'
  - '&e/f unclaim &8- &7Unclaim land from your faction.'
  - '&e/f kick &f<playerName> &8- &7Kick player from your faction.'
  - '&e/f mod &f<playerName> &8- &7Set player to mod role in faction.'
  - '&e/f coleader &f<playerName> &8- &7Set player to coleader role in faction.'
  - '&e/f leader &f<playerName> &8- &7Set player role to leader in faction.'
  - '&e/f chat &f<Faction | Ally | Public> &8- &7Switch to Faction/Ally/Public chat.'
  - '&e/f warp &8- &7Opens the warp menu.'
  - '&e/f setwarp &8- &7Set a warp.'
  - '&e/f perms &8- &7Change what players can do in your claims.'
  - '&e/f upgrades &8- &7Upgrade various perks in your faction.'
  - '&e/f checkpoint &8- &7Set a faction checkpoint.'
  - '&e/f tnt add/take &f<amount> &8- &7Faction Based TNT Bank.'
  - '&e/f tntfill &f<radius> <amount> &8- &7Tnt fill integrated into the tntbank!'
  - '&e/f chest &8- &7Open a virtual faction chest! '
  - '&e/f version &8- &7Display current faction version.'
  - '&7&m--------------------&r &e/f help 3 &7&m-----------------------'
fperm-gui:
  relation:
    name: Faction Permissions
    rows: 4
    slots:
      recruit: 10
      normal: 12
      moderator: 14
      coleader: 16
      truce: 19
      ally: 21
      enemy: 23
      neutral: 25
    materials:
      recruit: WOOD_SWORD
      normal: GOLD_SWORD
      moderator: IRON_SWORD
      coleader: DIAMOND_SWORD
      truce: IRON_AXE
      ally: GOLD_AXE
      enemy: DIAMOND_AXE
      neutral: WOOD_AXE
    dummy-items:
      '0':
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 11
      - 13
      - 15
      - 17
      - 20
      - 22
      - 24
      - 26
      - 17
      - 18
      - 19
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
    placeholder-item:
      name: '&8[{relation-color}{relation}&8]'
      lore:
      - null
  action:
    name: Faction Permissions
    rows: 6
    access:
      allow: LIME
      deny: RED
      undefined: CYAN
    slots:
      relation: 4
      back: 0
      build: 10
      destroy: 11
      frost-walk: 12
      pain-build: 13
      door: 14
      button: 15
      lever: 16
      container: 19
      invite: 20
      kick: 21
      item: 22
      sethome: 23
      withdraw: 24
      territory: 25
      access: 28
      promote: 29
      setwarp: 30
      warp: 31
      ban: 32
      disband: 33
      fly: 34
      vault: 40
      tntbank: 39
      tntfill: 41
      chest: 42
      spawner: 38
      home: 49
    materials:
      build: STAINED_GLASS
      destroy: STAINED_GLASS
      frost-walk: STAINED_GLASS
      pain-build: STAINED_GLASS
      door: STAINED_GLASS
      button: STAINED_GLASS
      lever: STAINED_GLASS
      container: STAINED_GLASS
      invite: STAINED_GLASS
      kick: STAINED_GLASS
      item: STAINED_GLASS
      sethome: STAINED_GLASS
      withdraw: STAINED_GLASS
      territory: STAINED_GLASS
      access: STAINED_GLASS
      promote: STAINED_GLASS
      setwarp: STAINED_GLASS
      warp: STAINED_GLASS
      ban: STAINED_GLASS
      disband: STAINED_GLASS
      fly: STAINED_GLASS
      vault: STAINED_GLASS
      tntbank: STAINED_GLASS
      tntfill: STAINED_GLASS
      chest: STAINED_GLASS
      spawner: STAINED_GLASS
      home: STAINED_GLASS
    dummy-items:
      '0':
      - 1
      - 2
      - 3
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 10
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
    placeholder-item:
      name: '&e&l(!) &ePermission: &6&n{action}'
      lore:
      - ''
      - '&6&l * &eStatus: &8[{action-access-color}{action-access}&8]'
      - ''
      - '&7Left click to &a&nAllow&7.'
      - '&7Right click to &c&nDeny&7.'
      - '&7Middle click to &7&nUndefine&7.'
  back-item:
    name: '&c&l<- Back'
    material: ARROW
    lore:
    - '&7Click to return to previous menu.'
  dummy-items:
    '0':
      material: STAINED_GLASS_PANE
      color: BLACK
      name: ' '
      lore:
      - null
fwarp-gui:
  name: Faction Warps
  rows: 3
  password-timeout: 5
  warp-slots:
  - 11
  - 12
  - 13
  - 14
  - 15
  dummy-slots:
    '0':
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
  warp-item:
    material: EYE_OF_ENDER
    name: '&e&l(!) &eFaction Warp: &6&n{warp}'
    lore:
    - ''
    - '&6&l * &ePassword: &7{warp-protected}'
    - '&6&l * &eCost: &7{warp-cost}'
    - ''
    - '&c&lNote: &7You need pay to teleport to'
    - '&7a faction warp. Unless it''s &nDisabled&7.'
  dummy-items:
    '0':
      material: STAINED_GLASS_PANE
      color: BLACK
      name: ' '
      lore:
      - null
deny-homes-in-system-factions: false
remove-homes-in-system-factions: false
deny-homes-in-enemy-factions: false
remove-homes-in-enemy-factions: false
deny-homes-in-neutral-factions: false
remove-homes-in-neutral-factions: false
deny-homes-in-ally-factions: false
remove-homes-in-ally-factions: false
deny-homes-in-truce-factions: false
remove-homes-in-truce-factions: false
faction-creation-broadcast: true
faction-disband-broadcast: true
See-Invisible-Faction-Members: false
frules:
  Enabled: true
  default-rules:
  - '&cDefault Faction Rules :('
  - '&cUse /f rules add <rule> to add a rule'
ftnt:
  Enabled: true
  Bank-Limit: 10000
fpaypal:
  Enabled: true
checkpoints:
  Enabled: true
fnear:
  Enabled: true
  Radius: 50
ffocus:
  Enabled: true
  Prefix: '&7»&b'
fvault:
  Enabled: true
  No-Hoppers-near-vault: true
  Price: 5000
  Item:
    Name: '&e&l*&f&l*&e&l* &e&lFaction Vault &7(Place) &e&l*&f&l*&e&l*'
    Lore:
    - '&7Place this vault in your Faction claim, You will'
    - '&7then be able to access it.'
    - ''
    - '&c&lNote: &7Once you have placed your'
    - '&7faction vault, Access it by doing /f vault.'
fchest:
  Enabled: true
  Inventory-Title: '&2&lFaction Chest'
fupgrades:
  Enabled: true
  MainMenu:
    Title: '{faction}''s Upgrade Menu'
    DummyItem:
      Name: '&f'
      Type: STAINED_GLASS_PANE
      Amount: 1
      Damage: 7
      Lore:
      - ''
      rows: 3
      slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
    Crops:
      Crop-Boost:
        level-1: 10
        level-2: 20
        level-3: 30
      Cost:
        level-1: 250000
        level-2: 500000
        level-3: 750000
      CropItem:
        Name: '&e&lUpgrade Growth Speed'
        Type: WHEAT
        Amount: 1
        Damage: 0
        Lore:
        - '&7Increase growth speed of crops in claims.'
        - '&7&o(Chance to Grow Two Levels)'
        - ''
        - '&e&lTier'
        - '&f&l* &7Current Level: &n{level}'
        - ''
        - '&e&lPerks'
        - '&f&l* &7Level 1 - &f10% Chance'
        - '&7  - Cost: $250,000'
        - '&f&l* &7Level 2 - &f20% Chance'
        - '&7  - Cost: $500,000'
        - '&f&l* &7Level 3 - &f30% Chance'
        - '&7  - Cost: $750,000'
        - ''
        - '&e&lClick to &nUnlock'
        slots:
        - 10
    EXP:
      EXP-Boost:
        level-1: 1.5
        level-2: 2.0
        level-3: 2.5
      Cost:
        level-1: 2000000
        level-2: 4000000
        level-3: 6000000
      EXPItem:
        Name: '&e&lUpgrade EXP Drop Rate'
        Type: EXP_BOTTLE
        Amount: 1
        Damage: 0
        Lore:
        - '&7Increased Vanilla XP gained from monsters.'
        - ''
        - '&e&lTier'
        - '&f&l* &7Current Level: &n{level}'
        - ''
        - '&e&lPerks'
        - '&f&l* &7Level 1 - &f1.5x Multiplier'
        - '&7  - Cost: $2,000,000'
        - '&f&l* &7Level 2 - &f2.0x Multiplier'
        - '&7  - Cost: $4,000,000'
        - '&f&l* &7Level 3 - &f2.5x Multiplier'
        - '&7  - Cost: $6,000,000'
        - ''
        - '&e&lClick to &nUnlock'
        slots:
        - 13
    Spawners:
      Spawner-Boost:
        level-1: 0.1
        level-2: 0.2
        level-3: 0.3
      Cost:
        level-1: 1000000
        level-2: 2000000
        level-3: 3000000
      SpawnerItem:
        Name: '&e&lUpgrade Spawn Rate'
        Type: MOB_SPAWNER
        Amount: 1
        Damage: 0
        Lore:
        - '&7Decreased mob spawner delay in claims.'
        - ''
        - '&e&lTier'
        - '&f&l* &7Current Level: &n{level}'
        - ''
        - '&e&lPerks'
        - '&f&l* &7Level 1 - &f10% Lower Delay'
        - '&7  - Cost: $1,000,000'
        - '&f&l* &7Level 2 - &f20% Lower Delay'
        - '&7  - Cost: $2,000,000'
        - '&f&l* &7Level 3 - &f30% Lower Delay'
        - '&7  - Cost: $3,000,000'
        - ''
        - '&e&lClick to &nUnlock'
        slots:
        - 16
    Chest:
      Chest-Size:
        level-1: 2
        level-2: 3
        level-3: 4
      Cost:
        level-1: 1000000
        level-2: 2000000
        level-3: 3000000
      ChestItem:
        Name: '&e&lUpgrade Faction Chest Size'
        Type: CHEST
        Amount: 1
        Damage: 0
        Lore:
        - '&7Increased Faction Chest Size.'
        - ''
        - '&e&lTier'
        - '&f&l* &7Current Level: &n{level}'
        - ''
        - '&e&lPerks'
        - '&f&l* &7Level 1 - &f2 Rows'
        - '&7  - Cost: $1,000,000'
        - '&f&l* &7Level 2 - &f3 Rows'
        - '&7  - Cost: $2,000,000'
        - '&f&l* &7Level 3 - &f4 Rows'
        - '&7  - Cost: $3,000,000'
        - ''
        - '&e&lClick to &nUnlock'
        slots:
        - 22
  upgrades:
    power:
      levels: {}
      displayitem: {}
    chest:
      levels: {}
      displayitem: {}
    exp:
      levels: {}
      displayitem: {}
    crop:
      levels: {}
      displayitem: {}
    member:
      levels: {}
      displayitem: {}
    spawner:
      levels: {}
      displayitem: {}
    tntbank:
      levels: {}
      displayitem: {}
    warp:
      levels: {}
      displayitem: {}
fbanners:
  Enabled: true
  Item:
    Name: '&e&l*&f&l*&e&l* &e&lWar Banner &7(Place) &e&l*&f&l*&e&l*'
    Lore:
    - '&7Place this banner in the &nWarzone.&7 This'
    - '&7will create a &nWarp Point&7 for your faction members.'
    - ''
    - '&e&lEffects'
    - '&e&l* &fStrength II'
    - '&e&l* &fSpeed II'
  Banner-Cost: 5000
  Banner-Time: 60
  Banner-Place-Cooldown: 300
  Banner-Effect-Radius: 16
  Effects:
  - INCREASE_DAMAGE:2
  - SPEED:2
  BannerHolo: '&c{Faction}''s War Banner'
  Placeable:
    Warzone: true
    Enemy: true
Title:
  Show-Title: true
  Options:
    FadeInTime: 1
    ShowTime: 10
    FadeOutTime: 1
  Format:
    Title: '{Faction}'
    Subtitle: '{Description}'
see-chunk:
  particles: true
  interval: 5
Tntfill:
  enabled: true
  max-radius: 32
  max-amount: 64
MassiveStats: true
